version: "3.9"

services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

  # traefik:
  #   image: traefik:v2.2
  #   ports:
  #     - 8008:80
  #     - 8081:8080
  #   volumes:
  #     - "./traefik.dev.toml:/etc/traefik/traefik.toml"
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"